"use client";
import { useCurrentUser } from "@/hooks/useCurrentUser";
import { Inter } from "next/font/google";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  useCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </header>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
